Repository AndresMpa/lyra, pull requests merged in 2024-05, with the labels that each got.

#1 Structuring
  .gitignore
  package.json
  pnpm-lock.yaml
Labels: documentation

#2 Basic server
  backend/main.py
Labels: enhancement

#3 Restructuring directories
  .gitignore
  client/assets/app/logo.png
  client/assets/figures/logo.png
  client/assets/fonts/Bukhari Script.ttf
  client/assets/fonts/BukhariScriptAlternates.ttf
  client/index.html
  client/main.js
  client/package.json
  client/pnpm-lock.yaml
  client/preloader/preload.js
  client/styles/basics.css
  client/styles/footer.css
  client/styles/logo.css
  client/styles/main.css
  client/styles/menu.css
  client/styles/message.css
  client/styles/navbar.css
  client/styles/prompt.css
  client/styles/widget.css
  client/utils/CPU.js
  client/utils/plots.js
  pnpm-lock.yaml
Labels: documentation

#4 Design guidelines
  .doc/README.md
  .doc/design.md
Labels: documentation

#6 Backend
  backend/.env.example
  backend/LlamadosExternos/FireBase.py
  backend/Secundarias.py
  backend/app.py
  backend/config/env_vars.py
  backend/main.py
  backend/requirements.txt
Labels: feature

#8 Tracking backend to the electron build
  client/main.js
  client/package.json
Labels: feature

#10 Updating README
  README.md
Labels: documentation

#12 Base url fix
  client/OS/baseLoader.js
  client/OS/main.js
  client/OS/plots.js
  client/config/default.json
  client/eventHandlers/prompt.js
  client/main.js
  client/preloader/preload.js
  client/utils/config.js
Labels: bug

#11 Update the model, clean of response and HTML format
  backend/Secundarias.py
  backend/app.py
  backend/config/env_vars.py
  backend/requirements.txt
Labels: bug, feature

#13 Quick fix
  client/main.js
Labels: bug

#14 Quick fixing
  client/eventHandlers/main.js
  client/eventHandlers/navbar.js
Labels: bug

#15 Fixing packages references
  README.md
Labels: documentation

#16 Update issue templates
  .github/ISSUE_TEMPLATE/community-bug.md
  .github/ISSUE_TEMPLATE/help-wanted.md
  .github/ISSUE_TEMPLATE/request-for-a-new-feature.md
Labels: documentation

#17 Create greetings.yml
  .github/workflows/greetings.yml
Labels: documentation

#18 Tracking setup for users
  README.md
Labels: documentation

#19 Fixes for building
  client/main.js
  client/package.json
  client/server/pythonManager.js
Labels: bug
